import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { Download, ArrowLeft, Layout, Printer, BookOpen } from 'lucide-react';
import toast from 'react-hot-toast';
import axios from 'axios';
import TemplateSelection from './resume/TemplateSelection';
import ResumeForm from './resume/ResumeForm';
import ResumePreview from './resume/ResumePreview';
import { TEMPLATES, generateAISummary, generateAISkills, generateAIProject, generateAIExperience } from './resume/ResumeTemplates';
import type { ResumeTemplate } from './resume/ResumeTemplates';

const courseThread = [
  { name: 'SDLC', path: '/courses?category=SDLC' },
  { name: 'HTML', path: '/courses?category=HTML' },
  { name: 'CSS', path: '/courses?category=CSS' },
  { name: 'Core Java', path: '/courses?category=Java' },
  { name: 'JavaScript', path: '/courses?category=JavaScript' },
  { name: 'Selenium', path: '/courses?category=Selenium' },
  { name: 'MySQL', path: '/courses?category=MySQL' },
  { name: 'Python', path: '/courses?category=Python' },
];

const ResumeBuilder = () => {
  const { user } = useAuth();
  const [step, setStep] = useState<'templates' | 'editor'>('templates');
  const [selectedTemplate, setSelectedTemplate] = useState<ResumeTemplate>(TEMPLATES[0]);
  const [aiLoading, setAiLoading] = useState<string | null>(null);

  const [formData, setFormData] = useState({
    fullName: user?.fullName || '',
    email: user?.email || '',
    phone: '',
    address: '',
    linkedin: '',
    github: '',
    title: '',
    summary: '',
    education: '',
    experience: '',
    languages: '',
    certifications: '',
  });

  const [skills, setSkills] = useState<string[]>([]);
  const [projects, setProjects] = useState([{ title: '', description: '', tech: '' }]);

  const triggerAI = (type: string) => {
    setAiLoading(type);
    setTimeout(() => {
      switch(type) {
        case 'summary': setFormData(f => ({ ...f, summary: generateAISummary(skills, formData.title, formData.experience) })); break;
        case 'skills': setSkills(s => [...new Set([...s, ...generateAISkills(s, formData.title)])]); break;
        case 'project': setProjects(p => [...p.filter(x => x.title), generateAIProject(skills, formData.title)]); break;
        case 'experience': setFormData(f => ({ ...f, experience: generateAIExperience(formData.title) })); break;
      }
      setAiLoading(null);
      toast.success('Generated! ✨');
    }, 1500);
  };

  const handleDownload = async () => {
    try {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF('p', 'mm', 'a4');
      const m = 15; let y = m;
      const c = selectedTemplate.colors;

      doc.setFillColor(parseInt(c.primary.slice(1,3),16), parseInt(c.primary.slice(3,5),16), parseInt(c.primary.slice(5,7),16));
      doc.rect(0, 0, 210, 35, 'F');
      doc.setTextColor(255,255,255); doc.setFontSize(22); doc.setFont('helvetica', 'bold');
      doc.text(formData.fullName || 'Name', m, 18);
      doc.setFontSize(9); doc.setFont('helvetica', 'normal');
      doc.text([formData.email, formData.phone, formData.address].filter(Boolean).join(' | '), m, 30);
      y = 45;

      const add = (t: string, ct: string) => {
        if (!ct?.trim()) return;
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFillColor(parseInt(c.heading.slice(1,3),16), parseInt(c.heading.slice(3,5),16), parseInt(c.heading.slice(5,7),16));
        doc.rect(m, y, 180, 0.5, 'F'); y += 4;
        doc.setTextColor(parseInt(c.heading.slice(1,3),16), parseInt(c.heading.slice(3,5),16), parseInt(c.heading.slice(5,7),16));
        doc.setFontSize(11); doc.setFont('helvetica', 'bold'); doc.text(t.toUpperCase(), m, y); y += 7;
        doc.setTextColor(60,60,60); doc.setFontSize(9); doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(ct, 180);
        lines.forEach((l: string) => { if (y > 275) { doc.addPage(); y = 20; } doc.text(l, m, y); y += 5; });
        y += 4;
      };

      add('Summary', formData.summary);
      if (skills.length) add('Skills', skills.join(' • '));
      add('Experience', formData.experience);
      add('Education', formData.education);
      const pt = projects.filter(p => p.title).map(p => `▸ ${p.title}\n  ${p.description}`).join('\n\n');
      add('Projects', pt);
      add('Languages', formData.languages);
      add('Certifications', formData.certifications);

      doc.setFontSize(7); doc.setTextColor(160,160,160);
      doc.text('Generated by CodeNexusLabs', m, 290);
      doc.save(`${(formData.fullName||'Resume').replace(/\s/g,'_')}.pdf`);
      toast.success('PDF downloaded!');
    } catch { toast.error('Download failed'); }
  };

  const saveResume = async () => {
    try {
      const token = localStorage.getItem('token') || sessionStorage.getItem('token');
      await axios.post('https://codenexuslabs-production.up.railway.app/api/v1/resumes/save', {
        fullName: formData.fullName, email: formData.email, phone: formData.phone,
        address: formData.address, title: formData.title, summary: formData.summary,
        skills: skills.join(', '), experience: formData.experience, education: formData.education,
        projects: JSON.stringify(projects), languages: formData.languages,
        certifications: formData.certifications, templateId: selectedTemplate.id,
      }, { headers: { Authorization: `Bearer ${token}` } });
      toast.success('Resume saved!');
    } catch { toast.error('Failed to save'); }
  };

  if (step === 'templates') {
    return (
      <div className="min-h-screen bg-gray-50">
        {/* Course Navigation Thread */}
        <div className="bg-white border-b border-gray-200 sticky top-0 z-40 shadow-sm">
          <div className="max-w-[1200px] mx-auto px-4 sm:px-6">
            <div className="flex items-center gap-1 overflow-x-auto py-2 scrollbar-hidden">
              <BookOpen className="w-4 h-4 text-indigo-500 flex-shrink-0 mr-1" />
              {courseThread.map((item) => (
                <Link
                  key={item.name}
                  to={item.path}
                  className="px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-all duration-200 flex-shrink-0 text-gray-600 hover:bg-indigo-50 hover:text-indigo-700"
                >
                  {item.name}
                </Link>
              ))}
            </div>
          </div>
        </div>
        <TemplateSelection onSelect={(tpl) => { setSelectedTemplate(tpl); setStep('editor'); }} />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Course Navigation Thread */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-40 shadow-sm">
        <div className="max-w-full mx-auto px-3">
          <div className="flex items-center gap-1 overflow-x-auto py-2 scrollbar-hidden">
            <BookOpen className="w-4 h-4 text-indigo-500 flex-shrink-0 mr-1" />
            {courseThread.map((item) => (
              <Link
                key={item.name}
                to={item.path}
                className="px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-all duration-200 flex-shrink-0 text-gray-600 hover:bg-indigo-50 hover:text-indigo-700"
              >
                {item.name}
              </Link>
            ))}
          </div>
        </div>
      </div>

      {/* Top Bar */}
      <div className="sticky top-[41px] z-30 bg-white border-b shadow-sm">
        <div className="max-w-full mx-auto px-3 h-12 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <button onClick={() => setStep('templates')} className="p-1.5 rounded-lg hover:bg-gray-100"><ArrowLeft className="w-4 h-4" /></button>
            <span className="text-sm font-semibold text-gray-700 hidden sm:block">{selectedTemplate.name}</span>
          </div>
          <div className="flex items-center gap-1.5">
            <button onClick={() => setStep('templates')} className="btn-secondary py-1.5 px-2.5 text-xs gap-1"><Layout className="w-3.5 h-3.5" /> Templates</button>
            <button onClick={() => window.print()} className="btn-secondary py-1.5 px-2.5 text-xs gap-1"><Printer className="w-3.5 h-3.5" /></button>
            <button onClick={saveResume} className="btn-secondary py-1.5 px-2.5 text-xs gap-1">💾 Save</button>
            <button onClick={handleDownload} className="btn-primary py-1.5 px-3 text-xs gap-1"><Download className="w-3.5 h-3.5" /> PDF</button>
          </div>
        </div>
      </div>

      {/* Main Editor */}
      <div className="flex flex-col lg:flex-row h-[calc(100vh-89px)]">
        <div className="lg:w-[42%] overflow-y-auto border-r border-gray-200 bg-white">
          <ResumeForm
            formData={formData} setFormData={setFormData}
            skills={skills} setSkills={setSkills}
            projects={projects} setProjects={setProjects}
            selectedTemplate={selectedTemplate}
            aiLoading={aiLoading} onAI={triggerAI}
          />
        </div>
        <div className="lg:flex-1 bg-gray-200 overflow-y-auto p-3 lg:p-4 flex items-start justify-center">
          <ResumePreview formData={formData} skills={skills} projects={projects} selectedTemplate={selectedTemplate} />
        </div>
      </div>
    </div>
  );
};

export default ResumeBuilder;