server.port=8080

# H2 for local development
spring.datasource.url=jdbc:h2:mem:codenexusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# JWT
app.jwtSecret=CodeNexusLabsSecretKeyForJWT2024VeryLongAndSecure123456789
app.jwtExpirationMs=86400000

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codenexuslabs.dev@gmail.com
spring.mail.password=qpnekccelfnizefo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Uploads
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/**
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.enabled=true

# Groq AI Configuration
groq.api.key=${GROQ_API_KEY}

# JDoodle API Credentials (Free - 200 executions/day)
JDoodle.CLIENT_ID=${5790d311dc30152d97e6ccf47a7eabfa}
JDoodle.CLIENT_SECRET=${ca57ec12c686f277e1152f281e48454e47e6e0fa68b9910cec0f5249595e9f98}