server.port=8080
spring.datasource.url=jdbc:h2:mem:codenexusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.web.cors.allowed-origins=http://localhost:3000
app.jwtSecret=CodeNexusLabsSecretKeyForJWT2024VeryLongAndSecure123456789
app.jwtExpirationMs=86400000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codenexuslabs.dev@gmail.com
spring.mail.password=qpnekccelfnizefo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/**